# Generated by Django 4.0.3 on 2022-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_bankaccount_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
