# Generated by Django 4.0.3 on 2022-04-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transections',
        ),
    ]
