# Generated by Django 4.0.3 on 2022-04-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_bankaccount_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='transections',
            name='show_to_user',
            field=models.BooleanField(default=True),
        ),
    ]
