# Generated by Django 4.0.3 on 2022-04-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_transections_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transections',
            name='account_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Accounts', to='accounts.bankaccount'),
        ),
    ]
