# Generated by Django 4.0.3 on 2022-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_transections_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transections',
            name='account_no',
            field=models.BigIntegerField(),
        ),
    ]
