# Generated by Django 4.0.3 on 2022-04-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_benificiary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benificiary',
        ),
    ]
