# Generated by Django 4.0.3 on 2022-04-02 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_delete_benificiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benificiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recievers_account_no', models.BigIntegerField()),
                ('IFSC_Code', models.CharField(max_length=10, unique=True)),
                ('max_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending')], default='Pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benificiary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
