# Generated by Django 4.0.3 on 2022-04-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_benificiary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benificiary',
        ),
    ]
